// A generic structure for all messages passed between scripts
export interface Message {
  type: string
  payload?: any
}

// The structure for a single result item to be displayed in the list
export interface CommandResult {
  id: string
  type: 'tab' | 'action' // A hint for the UI

  // Data needed for rendering, which the background will provide
  title: string
  subtitle?: string
  faviconUrl?: string

  // The executable part
  payload: {
    plan: PlanStep[]
  }
}

// A list of all valid primitive action names.
export const PrimitiveActions = ['FIND_TABS', 'GROUP_TABS', 'SWITCH_TO_TAB', 'CLOSE_TABS'] as const
export type PrimitiveAction = (typeof PrimitiveActions)[number]

// The structure for a single 'step' in a plan generated by the AI
export interface PlanStep {
  action: PrimitiveAction
  params: Record<string, any> // e.g., { query: 'github' } or { tabIds: '$PREVIOUS_RESULT' }
}
